CREATE DATABASE `dbtuts` ;
CREATE TABLE `dbtuts`.`users` ( `user_id` INT( 10 ) NOT NULL AUTO_INCREMENT PRIMARY KEY , 
`Name` VARCHAR( 25 ) NOT NULL , `Email` VARCHAR( 25 ) NOT NULL , 
`Email` VARCHAR( 45 ) NOT NULL,
`Gender` VARCHAR( 11 ) NOT NULL,
`Comment` VARCHAR( 45 )) ENGINE = InnoDB 